<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount' => '',
    'Amount Refunded' => '',
    'Amount Settle' => '',
    'Body' => '',
    'Channel' => '',
    'Channel Extra' => '',
    'Channel Id' => '',
    'Channel Identity' => '',
    'Channel Name' => '',
    'Charge ID' => '',
    'Charge Order No' => '',
    'Client Ip' => '',
    'Created At' => '',
    'Currency' => '',
    'Description' => '',
    'Extra' => '',
    'Failure Code' => '',
    'Failure Msg' => '',
    'Funding Source' => '',
    'Id' => '',
    'Metadata' => '',
    'Order No' => '',
    'Paid' => '',
    'Refunded' => '',
    'Reversed' => '',
    'Status' => '',
    'Subject' => '',
    'Succeed' => '',
    'Time Expire' => '',
    'Time Paid' => '',
    'Time Settle' => '',
    'Time Succeed' => '',
    'Transaction No' => '',
    'Updated At' => '',
    'User Id' => '',
];
