<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'App Id' => '应用ID',
    'Manage Transaction Withdrawal' => '提现管理',
    'Canceled At' => '取消时间',
    'Succeeded At' => '成功时间',
    'Update Transaction Withdrawal' => '更新提现',
    'Alipay Pid' => '支付宝合作者PID',
    'MchId' => '商户号',
    'Create Transaction Withdrawal' => '发起提现申请',
    'Amount' => '金额',
    'Extra' => '附加参数',
    'Subject' => '标题',
    'User Id' => '用户ID',
    'PrivateKey' => '私钥',
    'PublicKey' => '公钥',
    'Sign Type' => '签名类型',
    'Amount Refunded' => '退款金额',
    'Amount Settle' => '',
    'Configuration Transaction Channel' => '渠道参数配置',
    'Batch Deletion' => '批量删除',
    'Body' => '订单内容',
    'Configuration success.' => '配置成功！',
    'Channel Name' => '渠道名称',
    'Unsettled Funds' => '使用未结算资金',
    'Recharge Funds' => '使用可用余额',
    'Pending' => '等待处理',
    'Succeeded' => '处理完成',
    'Failed' => '处理失败',
    'Charge ID' => '支付ID',
    'Charge Order No' => '订单号',
    'Change transaction has not yet been paid and cannot be refunded.' => '交易尚未支付，无法退款。',
    'Client Ip' => '客户IP',
    'Failure Code' => '失败代码',
    'Failure Msg' => '失败消息',
    'Funding Source' => '资金来源',
    'Alipay Account' => '支付宝账号',
    'Metadata' => '元数据',
    'Order No' => '订单号',
    'Timeout' => '连接超时时间',
    'Channel Configuration' => '渠道配置',
    'Paid' => '已付款',
    'Refunded' => '存在退款',
    'Reversed' => '已撤销',
    'Status' => '状态',
    'Alipay PublicKey' => '支付宝公钥',
    'Succeed' => '成功',
    'Time Expire' => '过期时间',
    'Time Paid' => '付款时间',
    'Charge Notice Route' => '交易通知路由',
    'Refund Notice Route' => '退款通知路由',
    'Charge Return Route' => '交易返回路由',
    'Time Settle' => '',
    'Time Succeed' => '成功时间',
    'Transaction No' => '支付渠道流水号',
    'Update Transaction Channel' => '更新渠道配置',
    'Update Transaction Charge' => '修改支付',
    'Update Transaction Refund' => '修改退款',
    'Channel' => '渠道',
    'Channel ClassName' => '渠道类名',
    'Channel Identity' => '渠道标识',
    'Channel Title' => '渠道标题',
    'Configuration' => '配置',
    'Create Transaction Channel' => '创建交易渠道',
    'Create Transaction Charge' => '创建付款',
    'Create Transaction Refund' => '创建退款',
    'Created At' => '创建时间',
    'Currency' => '币种',
    'Delete Transaction Channel' => '删除交易渠道',
    'Delete Transaction Charge' => '删除付款',
    'Delete Transaction Refund' => '删除退款',
    'Description' => '描述',
    'Manage Transaction Channel' => '支付渠道管理',
    'Manage Transaction Charge' => '支付管理',
    'Manage Transaction Refund' => '退款管理',
    'Updated At' => '更新时间',
    '\'{class}\' must extend from \'yuncms\\transaction\\contracts\\ChannelInterface\' or its child class' => '\'{class}\' 必须从 \'yuncms\\transaction\\contracts\\ChannelInterface\' 或其子类继承'
];
