<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount' => '',
    'Amount Refunded' => '',
    'Amount Settle' => '',
    'Batch Deletion' => '',
    'Body' => '',
    'Channel Name' => '渠道名称',
    'Charge ID' => '',
    'Charge Order No' => '',
    'Client Ip' => '',
    'Failure Code' => '',
    'Failure Msg' => '',
    'Funding Source' => '',
    'Metadata' => '',
    'Order No' => '',
    'Paid' => '',
    'Refunded' => '',
    'Reversed' => '',
    'Status' => '',
    'Subject' => '',
    'Succeed' => '',
    'Time Expire' => '',
    'Time Paid' => '',
    'Time Settle' => '',
    'Time Succeed' => '',
    'Transaction No' => '',
    'Update Transaction Channel' => '更新渠道配置',
    'Update Transaction Charge' => '修改支付',
    'Update Transaction Refund' => '修改退款',
    'Channel' => '渠道',
    'Channel ClassName' => '渠道类名',
    'Channel Identity' => '渠道标识',
    'Channel Title' => '渠道标题',
    'Configuration' => '配置',
    'Create Transaction Channel' => '创建交易渠道',
    'Create Transaction Charge' => '创建付款',
    'Create Transaction Refund' => '创建退款',
    'Created At' => '创建时间',
    'Currency' => '币种',
    'Delete Transaction Channel' => '删除交易渠道',
    'Delete Transaction Charge' => '删除付款',
    'Delete Transaction Refund' => '删除退款',
    'Description' => '描述',
    'Manage Transaction Channel' => '支付渠道管理',
    'Manage Transaction Charge' => '支付管理',
    'Manage Transaction Refund' => '退款管理',
    'Updated At' => '更新时间',
];
